//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedicaKenny
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicaMedicaEntities1 : DbContext
    {
        public ClinicaMedicaEntities1()
            : base("name=ClinicaMedicaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONSULTA> CONSULTA { get; set; }
        public virtual DbSet<ESPECIALIDADE> ESPECIALIDADE { get; set; }
        public virtual DbSet<MEDICO> MEDICO { get; set; }
        public virtual DbSet<MEDICO_ESPECIALIDADE> MEDICO_ESPECIALIDADE { get; set; }
        public virtual DbSet<PACIENTE> PACIENTE { get; set; }
        public virtual DbSet<TELEFONE_MEDICO> TELEFONE_MEDICO { get; set; }
        public virtual DbSet<TIPO_SANGUE> TIPO_SANGUE { get; set; }
    }
}
