//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedicaKenny
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.CONSULTA = new HashSet<CONSULTA>();
        }
    
        public string DS_CODIGO { get; set; }
        public string NM_NOME { get; set; }
        public string DS_ENDERECO { get; set; }
        public string NR_TELEFONE { get; set; }
        public int ID_PACIENTE { get; set; }
        public Nullable<int> ID_TIPO_SANGUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA> CONSULTA { get; set; }
        public virtual TIPO_SANGUE TIPO_SANGUE { get; set; }
    }
}
