//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMedicaKenny
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONE_MEDICO
    {
        public string NR_TELEFONE { get; set; }
        public int ID_TELEFONE_MEDICO { get; set; }
        public string NR_CRM { get; set; }
    
        public virtual MEDICO MEDICO { get; set; }
    }
}
